# Generated by Django 3.1.1 on 2020-09-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(default='http://www.google.com', max_length=256, unique=True, verbose_name='URL')),
                ('short_url', models.CharField(default='http://127.0.0.1:8000/urlshortner/rdfyu', max_length=256)),
                ('number_hits', models.IntegerField()),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
