# Generated by Django 3.1.1 on 2020-09-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0002_auto_20200905_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldetails',
            name='short_url',
            field=models.CharField(max_length=256),
        ),
    ]
