# Generated by Django 3.1.1 on 2020-09-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0003_auto_20200905_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldetails',
            name='number_hourly_hits',
            field=models.IntegerField(default=0),
        ),
    ]
